#!/usr/bin/env bash
# Configures an Ubuntu server with custom IP resolution
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/g' ~/hosts.new
echo "8.8.8.8\tfacebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
